### ISSUE TITLE
error on opening

### ISSUE THREAD

**Issue by m4b** [vibhavp/emacs-lsp#2] opened 2016-12-09 04:43 UTC
When i navigate to a rust project, open say `lib.rs` on initial open i get:

```
let: Symbol’s function definition is void: hash-table-keys
```

the `rls` binary is in my `/home/m4b/bin` which is in my `$PATH`

this is in my `.emacs`

```
;; lsp
(add-to-list 'load-path "/home/m4b/git/emacs-lsp")
(require 'lsp-mode)
(global-lsp-mode t)
```

am I doing something wrong?

**Comment by vibhavp** [comment] 2016-12-09 06:42
Try adding `(require 'subr-x)` to`lsp-document.el? I should be testing more on `emacs -Q`.

**Comment by vibhavp** [comment] 2016-12-09 12:09
Should be fixed in 68fcee992ec73bfcfd828955bf78089d3c26fccb

**Comment by m4b** [comment] 2016-12-09 18:43
I receive this error on opening now:

```
aset: Wrong type argument: hash-table-p, nil
```

**Comment by vibhavp** [comment] 2016-12-10 04:56
Hm, I cannot reproduce it on `emacs -Q` with 25.1. Are you on the latest commit?

**Comment by m4b** [comment] 2016-12-10 05:18
not sure what you mean by using `emacs -Q`; this won't load the `.emacs` file irrc, so the mode won't load properly.  How are  you testing this exactly?

I do:

```
emacs
C-x C-f <path/to/lib.rs> <RET>
```

and error occurs as described when I uncomment this at the bottom of my `.emacs`:

```
;; lsp
;; (add-to-list 'load-path "/home/m4b/git/emacs-lsp")
;; (require 'lsp-mode)
;; (global-lsp-mode t)

;; (toggle-debug-on-error)
```

My emacs version:

```
emacs --version
GNU Emacs 25.1.1
Copyright (C) 2016 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

my rustls is in `~/bin/` and execs properly, and emacs knows about my `~/bin`.

Is there a particular sequence you use to test?

**Comment by vibhavp** [comment] 2016-12-10 05:52
This is what I use:
```emacs-lisp
(package-initialize)
(add-to-list 'load-path "~/src/emacs-lsp")
(require 'lsp-mode)
(global-lsp-mode)
(add-to-list 'exec-path "~/bin") ;;; path to rls
(toggle-debug-on-error t)
```

**Comment by vibhavp** [comment] 2016-12-10 06:24
hm, I can reproduce this with Go's Language Server too

**Comment by vibhavp** [comment] 2016-12-10 06:37
This should have fixed it, could you try again?

**Closed** 2016-12-10 06:36 UTC

**Comment by m4b** [comment] 2016-12-10 20:49
This seems to execute the process correctly now, but whenever I type I get pairs of:

```
Unknown notification rustDocument/diagnosticsEnd
```

and `Begin`

**Comment by vibhavp** [comment] 2016-12-11 04:20
Should be fixed.

**Comment by m4b** [comment] 2016-12-15 08:54
latest changes seem to have resolved an infinite gc collection/infinite loop i was seeing before. seems to start correctly now

**Comment by vibhavp** [comment] 2016-12-15 12:37
Btw, to avoid getting into an infinite loop with rls, you need to remove the println! statement in build.rs and action.rs. Printing non-LSP stuff to stdio confuses the parser.

**Comment by m4b** [comment] 2016-12-16 03:41
Wow that's kind of a problem? Everything in a build.rs outlets to stdout iirc, eg linking directives to cargo, static library locations, etc., unless I'm misunderstanding?

**Comment by vibhavp** [comment] 2016-12-16 04:12
Oops, just make that action.rs. build.rs shouldn't be an issue.

**Comment by vibhavp** [comment] 2016-12-16 05:03
Disregard that^

What happens is that when any non LSP stuff is printed to stdout, it messes with the parser, making it reject any response that might be getting printed. This results in lsp-mode hanging up, as it waits for the response it just rejected. Specifically, you need to comment out the `println!`s in https://github.com/jonathandturner/rls/blob/6f46a9f3b1917699d42351301a58269ab83b3ad8/src/actions.rs#L66 and https://github.com/jonathandturner/rls/blob/dcf061c526ce37c3d4c5f17d0f135c9435c48cbf/src/build.rs#L374

**Comment by m4b** [comment] 2016-12-16 06:47
Wow are you serious? You should open an issue in rls I think?

**Comment by vibhavp** [comment] 2016-12-16 06:54
Yep, commenting those two lines out and building rls stops emacs-lsp from freezing up randomly, to the point where I could work on a [rust project of mine without issues](https://github.com/vibhavp/engine.io-rs). I'll file a bug in rls about this.

**Comment by m4b** [comment] 2016-12-16 07:56
I think you definitely found a bug; what's weird is that i was on commit 131f090 and it had those lines commented (and action.rs hadn't been invented yet), so I think this was an accidental regression on their side.

However, it still had the long pauses.

I've recompiled the latest lsp without any `println!` and my emacs is currently using 100% cpu after scrolling a buffer; eldoc seemed to work, didn't try completion, scrolled and hover started the loop.
